# Generated by Django 5.2 on 2025-05-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='city',
            field=models.CharField(default='London', max_length=100),
        ),
    ]
