# Generated by Django 5.2 on 2025-05-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_footballclub_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclub',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
